
import { VerticalBox, HorizontalBox} from "std-widgets.slint";
import { SIcon } from "../modules/surrealism-ui/index.slint";
import { UseIcons } from "../modules/surrealism-ui/use/src/icon.slint";

export component Collapse inherits VerticalBox {
    width: 100%;
    padding: 0px;

    in property <string> title;
    in property <image> icon;
    in property <length> header-height;
    in property <length> content-height;

    in-out property <bool> expanded;

    Rectangle {
        width: 100%;
        height: header-height;
        border-color: red;
        border-width: 1px;
        SIcon {
            x: 0;
            source: icon;
            height: 64px;
            width: 64px;
        }

        Text {
            x: 68px;
            text: title;
            vertical-alignment: TextVerticalAlignment.center;
            horizontal-alignment: TextHorizontalAlignment.left;
        }

        SIcon {
            x: parent.width - 44px;
            source: expanded ? UseIcons.icons.Up : UseIcons.icons.Down;
            height: 24px;
            width: 24px;
        }

        TouchArea {
            mouse-cursor: MouseCursor.pointer;
            clicked => {
                expanded = !expanded;
            }
        }
    }

    content := VerticalBox {
        visible: expanded;
        height: expanded ? content-height : 0;

        @children
    }
}
