import { StandardTableView } from "std-widgets.slint";
export component RoomsFileExplorer inherits Window {
    StandardTableView {
        y: 0;
        width: 100%;
        height: 100%;
        columns: [
            { title: "Header 1" },
            { title: "Header 2" },
        ];
        rows: [
            [
                { text: "Item 1" },
                { text: "Item 2" },
            ],
            [
                { text: "Item 1" },
                { text: "Item 2" },
            ],
            [
                { text: "Item 1" },
                { text: "Item 2" },
            ]
        ];
    }
}
