import { SButton, SCard, SIcon } from "../modules/surrealism-ui/index.slint";
import { UseIcons } from "../modules/surrealism-ui/use/src/icon.slint";
import { HorizontalBox, VerticalBox, LineEdit, Button } from "std-widgets.slint";
import { RoomsFileExplorer } from "../components/rooms-file-explorer.slint";
import { Collapse } from "../components/collapse.slint";

export component MainView {
    y: 0;
    preferred-height: 100%;
    preferred-width: 100%;

    in property <string> main_dir;

    VerticalLayout {
        padding: 10px;

        HorizontalBox {
            height: 50px;
            Text {
                vertical-alignment: TextVerticalAlignment.center;
                text: "Easy Rooms:";
            }

            LineEdit {
                font-size: 14px;
                placeholder-text: "Selecciona la ruta de la partición o un directorio con los archivos de esta...";
                text: main_dir;
            }

            Button {
                colorize-icon: false;
                enabled: true;
                icon: @image-url("../icons/folder_open.svg");
                primary: false;
                text: "Abrir";
            }
        }

        HorizontalBox {
            padding-top: 10px;

            SCard {
                width: 50%;

                Collapse {
                    title: "Nintendo 64";
                    icon: @image-url("../icons/n64.svg");
                    header-height: 50px;
                    content-height: 300px;

                    VerticalBox {
                        padding: 10px;
                        SButton {
                            text: "Crear carpeta";
                        }

                        RoomsFileExplorer { }
                    }
                }

                RoomsFileExplorer { }
            }

            VerticalBox {
                Image {
                    source: @image-url("../icons/folder_open.svg");
                }
            }
        }
    }
}
