import { SButton, SCard, SIcon } from "../modules/surrealism-ui/index.slint";
import { UseIcons } from "../modules/surrealism-ui/use/src/icon.slint";
import { HorizontalBox, VerticalBox, LineEdit, Button } from "std-widgets.slint";
import { RoomsFileExplorer } from "../components/rooms-file-explorer.slint";
import { Collapse } from "../components/collapse.slint";

export component MainView {
    y: 0;
    preferred-height: 100%;
    preferred-width: 100%;

    in property <string> main_dir;

    VerticalLayout {
        padding: 10px;

        HorizontalBox {
            height: 50px;
            Text {
                vertical-alignment: TextVerticalAlignment.center;
                text: "Easy Rooms:";
            }

            LineEdit {
                font-size: 14px;
                placeholder-text: "Selecciona la ruta de la partición o un directorio con los archivos de esta...";
                text: main_dir;
            }

            Button {
                colorize-icon: false;
                enabled: true;
                icon: @image-url("../icons/folder_open.svg");
                primary: false;
                text: "Abrir";
            }
        }

        HorizontalLayout {
            padding-top: 10px;
            SCard {
                width: 50%;

                Rectangle {
                    width: 100%;
                    height: 50px;
                    TouchArea {
                        height: 100%;
                        width: 100%;
                        mouse-cursor: MouseCursor.pointer;

                        SIcon {
                            x: 0;
                            source: @image-url("../icons/n64.svg");
                            height: 64px;
                            width: 64px;
                        }

                        Text {
                            x: 68px;
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.left;
                            text: "Nintendo 64";
                        }

                        SIcon {
                            x: parent.width - 44px;
                            source: UseIcons.icons.Down;
                            height: 24px;
                            width: 24px;
                        }
                    }
                }

                Collapse {
                    expanded: false;
                    title: "Nintendo 64";
                    icon: @image-url("../icons/n64.svg");
                    header-height: 50px;
                }

                RoomsFileExplorer { }
            }

            VerticalBox {
                Image {
                    source: @image-url("../icons/folder_open.svg");
                }
            }
        }
    }
}
